apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: cinema
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 979050235289.dkr.ecr.ap-northeast-2.amazonaws.com/user03-gateway:v1
          ports:
            - containerPort: 8080