apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: cinema
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: 979050235289.dkr.ecr.ap-northeast-2.amazonaws.com/user03-payment:v1
          ports:
            - containerPort: 8080
          env:
			      # cofingmap에 있는 단일 key-value
            - name: MAX_RESERVATION_PER_PERSION
              valueFrom:
                configMapKeyRef:
                  name: cinema-config
                  key: max_reservation_per_person
            - name: UI_PROPERTIES_FILE_NAME
              valueFrom:
                configMapKeyRef:
                  name: cinema-config
                  key: ui_properties_file_name
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: aws-efs
          readinessProbe:  # killing -> restart
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:   # health Check 
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

        